# -*- coding: utf-8 -*-
"""Contador_de_faltas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ycJujThnScAkYrrWNEEDyymSbiNfEVkm
"""

numero_aulas = 92
numero_faltas = 8

limite_faltas = int(numero_aulas * 0.3)

frequencia = ((numero_aulas - numero_faltas) / numero_aulas) * 100

print(f"Frequência: {frequencia:.2f}%")

if numero_faltas < limite_faltas:
    print("Está dentro do limite de faltas.")
elif numero_faltas == limite_faltas:
    print("Você não pode faltar mais.")
else:
    print("Reprovou por falta.")